// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'frb_engine/flutter_rust_bridge.dart';
import 'bridge_generated_web.web.dart';

final api = BridgeImpl.wasm(
  WasmModule.initialize(kind: const Modules.noModules(root: 'pkg/hub')),
);
