// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'frb_engine/exports.dart';
import 'bridge_web_generated.dart';

final api = BridgeWebImpl.wasm(
  WasmModule.initialize(kind: const Modules.noModules(root: 'pkg/hub')),
);
