// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.78.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class Bridge {
  Stream<RustSignal> prepareRustSignalStream({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPrepareRustSignalStreamConstMeta;

  Stream<RustResponseUnique> prepareRustResponseStream({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPrepareRustResponseStreamConstMeta;

  void prepareChannels({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPrepareChannelsConstMeta;

  Future<void> startRustLogic({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStartRustLogicConstMeta;

  void requestToRust({required RustRequestUnique requestUnique, dynamic hint});

  FlutterRustBridgeTaskConstMeta get krequestToRustConstMeta;
}

enum Operation {
  Create,
  Read,
  Update,
  Delete,
}

class RustRequest {
  final String address;
  final Operation operation;
  final Uint8List bytes;

  const RustRequest({
    required this.address,
    required this.operation,
    required this.bytes,
  });
}

class RustRequestUnique {
  final int id;
  final RustRequest request;

  const RustRequestUnique({
    required this.id,
    required this.request,
  });
}

class RustResponse {
  final bool successful;
  final Uint8List bytes;

  const RustResponse({
    required this.successful,
    required this.bytes,
  });
}

class RustResponseUnique {
  final int id;
  final RustResponse response;

  const RustResponseUnique({
    required this.id,
    required this.response,
  });
}

class RustSignal {
  final String address;
  final Uint8List bytes;

  const RustSignal({
    required this.address,
    required this.bytes,
  });
}
