// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.80.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "definitions.dart";
import 'dart:convert';
import 'dart:async';

import '../engine/exports.dart';
import 'generated.io.dart' if (dart.library.html) 'generated.web.dart';

class BridgeImpl implements Bridge {
  final BridgePlatform _platform;
  factory BridgeImpl(ExternalLibrary dylib) =>
      BridgeImpl.raw(BridgePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory BridgeImpl.wasm(FutureOr<WasmModule> module) =>
      BridgeImpl(module as ExternalLibrary);
  BridgeImpl.raw(this._platform);
  Stream<RustSignal> prepareRustSignalStream({dynamic hint}) {
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_prepare_rust_signal_stream(port_),
      parseSuccessData: _wire2api_rust_signal,
      constMeta: kPrepareRustSignalStreamConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kPrepareRustSignalStreamConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "prepare_rust_signal_stream",
        argNames: [],
      );

  Stream<RustResponseUnique> prepareRustResponseStream({dynamic hint}) {
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_prepare_rust_response_stream(port_),
      parseSuccessData: _wire2api_rust_response_unique,
      constMeta: kPrepareRustResponseStreamConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kPrepareRustResponseStreamConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "prepare_rust_response_stream",
        argNames: [],
      );

  Stream<String> prepareRustReportStream({dynamic hint}) {
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_prepare_rust_report_stream(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kPrepareRustReportStreamConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kPrepareRustReportStreamConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "prepare_rust_report_stream",
        argNames: [],
      );

  Future<void> prepareChannels({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_prepare_channels(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kPrepareChannelsConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kPrepareChannelsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "prepare_channels",
        argNames: [],
      );

  Future<bool> checkRustStreams({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_check_rust_streams(port_),
      parseSuccessData: _wire2api_bool,
      constMeta: kCheckRustStreamsConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCheckRustStreamsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "check_rust_streams",
        argNames: [],
      );

  Future<void> startRustLogic({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_start_rust_logic(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kStartRustLogicConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStartRustLogicConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "start_rust_logic",
        argNames: [],
      );

  Future<void> stopRustLogic({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_stop_rust_logic(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kStopRustLogicConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStopRustLogicConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "stop_rust_logic",
        argNames: [],
      );

  Future<void> requestToRust(
      {required RustRequestUnique requestUnique, dynamic hint}) {
    var arg0 =
        _platform.api2wire_box_autoadd_rust_request_unique(requestUnique);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_request_to_rust(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kRequestToRustConstMeta,
      argValues: [requestUnique],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRequestToRustConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "request_to_rust",
        argNames: ["requestUnique"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  RustResponse _wire2api_box_autoadd_rust_response(dynamic raw) {
    return _wire2api_rust_response(raw);
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  RustResponse? _wire2api_opt_box_autoadd_rust_response(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_rust_response(raw);
  }

  Uint8List? _wire2api_opt_uint_8_list(dynamic raw) {
    return raw == null ? null : _wire2api_uint_8_list(raw);
  }

  RustResponse _wire2api_rust_response(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustResponse(
      message: _wire2api_opt_uint_8_list(arr[0]),
      blob: _wire2api_opt_uint_8_list(arr[1]),
    );
  }

  RustResponseUnique _wire2api_rust_response_unique(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustResponseUnique(
      id: _wire2api_i32(arr[0]),
      response: _wire2api_opt_box_autoadd_rust_response(arr[1]),
    );
  }

  RustSignal _wire2api_rust_signal(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustSignal(
      resource: _wire2api_i32(arr[0]),
      message: _wire2api_opt_uint_8_list(arr[1]),
      blob: _wire2api_opt_uint_8_list(arr[2]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

int api2wire_i32(int raw) {
  return raw;
}

int api2wire_rust_operation(RustOperation raw) {
  return api2wire_i32(raw.index);
}

int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
