import 'dart:typed_data';

/// This type represents a function
/// that can accept raw signal data from Rust
/// and handle it accordingly.
typedef AssignRustSignal = Map<String, Function(Uint8List, Uint8List)>;

/// This contains a message from Rust.
/// Optionally, a custom binary called `binary` can also be included.
/// This type is generic, and the message
/// can be of any type declared in Protobuf.
class RustSignal<T> {
  /// The message instance of a class generated by Protobuf.
  final T message;

  /// Binary data included in the signal.
  /// This field is useful for sending custom bytes
  /// without the overhead of serialization/deserialization.
  final Uint8List binary;

  RustSignal(this.message, this.binary);
}
